apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: nittfest
  labels:
    app: order-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: anshul8394/order-service:1
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: nfconfigmap
