kind: Deployment
apiVersion: apps/v1
metadata:
  name: nf-deployemnt
  namespace: nittfest
  labels: 
    app: nittfest
specs:
  replicas: 3
  selectors:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nittfest
    spec:
      containers:
        - name: frontend
          image: anshul8394/frontend:1
          ports:
            containerPort: 80

