apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: nittfest
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: anshul8394/frontend:1
          ports:
            - containerPort: 5173
          envFrom:
            - configMapRef:
                name: nfconfigmap
