kind: ConfigMap
apiVersion: v1
metadata:
  name: nfconfigmap
data:
  USER_SERVICE_URL: "http://user-service:8081"
  VITE_USER_SERVICE_URL: "http://13.126.215.91:30316"
  VITE_ORDER_SERVICE_URL: "http://13.126.215.91:30316"

