apiVersion: v1
kind: ConfigMap
metadata:
  name: nfconfigmap
  namespace: nittfest
data:
  USER_SERVICE_URL: "http://user-service:8081"
  VITE_USER_SERVICE_URL: "/api/users"
  VITE_ORDER_SERVICE_URL: "/api/orders"
